name: Gradle build on push
run-name: Pushed to ${{ github.repository }} by ${{ github.actor }} 🚀
on: [push]
jobs:
  gradle_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Execute Java version
        run: java --version
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
      - name: Execute Gradle version
        run: ./gradlew --version
      - name: Execute Gradle build
        run: ./gradlew build